[package]
name = "oxipresso-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "oxipresso"
path = "src/main.rs"

[[bin]]
name = "oxipresso-viewer"
path = "src/viewer.rs"
required-features = ["gui"]

[features]
default = []
gui = ["oxipresso-viewer/gui"]
pdfium = ["oxipresso-render/pdfium", "oxipresso-viewer/pdfium"]
pdfium-bundled = ["pdfium", "oxipresso-render/pdfium-bundled", "oxipresso-viewer/pdfium-bundled"]

[dependencies]
oxipresso-editor-protocol = { path = "../oxipresso-editor-protocol" }
oxipresso-engine-api = { path = "../oxipresso-engine-api" }
oxipresso-engine-external = { path = "../oxipresso-engine-external" }
oxipresso-engine-xetex = { path = "../oxipresso-engine-xetex" }
oxipresso-platform = { path = "../oxipresso-platform" }
oxipresso-render = { path = "../oxipresso-render" }
oxipresso-synctex = { path = "../oxipresso-synctex" }
oxipresso-vfs = { path = "../oxipresso-vfs" }
oxipresso-viewer = { path = "../oxipresso-viewer" }

[dev-dependencies]
oxipresso-testkit = { path = "../oxipresso-testkit" }
